/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Dao.ItensCompraDao;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guilherme.santos
 */
public class TelaItensCompra extends javax.swing.JFrame {

    /**
     * Creates new form ItensVenda
     */
    String CodCompra2;
    String ValorItemConvertido;
    Double TotalItem;

    public TelaItensCompra() {
        initComponents();
        PegarCodCompra();
    }

    //Pega o codigo da compra que está na tela de compras
    public void PegarCodCompra() {
        TelaCompra m = new TelaCompra();
        CodCompra2 = Integer.toString(m.CodCompra);
    }
//carrega Tabela

    public void MostrarItens() {
        JTItensCompra.getColumnModel().getColumn(0).setPreferredWidth(60);
        JTItensCompra.getColumnModel().getColumn(1).setPreferredWidth(100);
        JTItensCompra.getColumnModel().getColumn(2).setPreferredWidth(70);
        JTItensCompra.getColumnModel().getColumn(2).setPreferredWidth(70);
        DefaultTableModel modelo = (DefaultTableModel) JTItensCompra.getModel();
        modelo.setNumRows(0);
        ItensCompraDao cdao = new ItensCompraDao();

        cdao.BuscarItensCompra(Integer.parseInt(CodCompra2)).forEach((c) -> {
            modelo.addRow(new Object[]{
                c.getCod_item_compra(),
                c.getDescricao_item_compra(),
                c.getQuantidade(),
                c.getValor_item_compra(),
                c.getValor_total_item_compra()
            });
        });
    }

    //Salvar Item da Venda
    public void SalvarItemCompra() {
        Modelo.ItensCompra i = new Modelo.ItensCompra();
        ItensCompraDao idao = new ItensCompraDao();
        if (TxtDescItem.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Descrição do item é obrigatório!");
            TxtDescItem.requestFocus();
        } else if (TxtValorItem.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Valor de Venda do item é obrigatório!");
            TxtValorItem.requestFocus();
        } else if (TxtQuantidadeItem.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Quantidade do item é obrigatório!");
            TxtQuantidadeItem.requestFocus();
        }

        i.setDescricao_item_compra(TxtDescItem.getText());
        i.setCod_compra(Integer.parseInt(CodCompra2));
        i.setQuantidade(Integer.parseInt(TxtQuantidadeItem.getText()));
        i.setValor_item_compra(Double.parseDouble(TxtValorItem.getText()));
        i.setValor_total_item_compra(Double.parseDouble(LbValorTotalItem.getText()));
        idao.SalvarItem(i);
        LimparCamposItens();
        MostrarItens();
    }

    public void LimparCamposItens() {
        TxtDescItem.setText("");
        TxtValorItem.setText("");
        TxtQuantidadeItem.setText("");
        LbValorTotalItem.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TxtDescItem = new javax.swing.JTextField();
        TxtValorItem = new javax.swing.JTextField();
        TxtQuantidadeItem = new javax.swing.JTextField();
        jBInserir = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        LbValorTotalItem = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTItensCompra = new javax.swing.JTable();
        jBFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Itens da Compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 14))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel7.setText("Descrição");

        jLabel9.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel9.setText("Valor Item");

        jLabel10.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel10.setText("Quantidade");

        TxtValorItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtValorItemKeyReleased(evt);
            }
        });

        TxtQuantidadeItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtQuantidadeItemActionPerformed(evt);
            }
        });
        TxtQuantidadeItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtQuantidadeItemKeyReleased(evt);
            }
        });

        jBInserir.setText("Inserir");
        jBInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInserirActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel16.setText("Valor Total");

        LbValorTotalItem.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        LbValorTotalItem.setForeground(new java.awt.Color(0, 102, 255));

        JTItensCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Qtd", "Valor Unt", "Valor Total"
            }
        ));
        JTItensCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JTItensCompra.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(JTItensCompra);

        jBFinalizar.setText("Finalizar");
        jBFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel16)
                    .addComponent(jLabel7))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtDescItem)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtValorItem, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtQuantidadeItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(LbValorTotalItem, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TxtDescItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TxtValorItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtQuantidadeItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LbValorTotalItem, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtValorItemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtValorItemKeyReleased
        ValorItemConvertido = String.valueOf(TxtValorItem.getText());
        ValorItemConvertido = ValorItemConvertido.replaceAll(",", ".");

        DecimalFormat df = new DecimalFormat();
        df.setMaximumFractionDigits(2);

    }//GEN-LAST:event_TxtValorItemKeyReleased

    private void TxtQuantidadeItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtQuantidadeItemActionPerformed

    }//GEN-LAST:event_TxtQuantidadeItemActionPerformed

    private void TxtQuantidadeItemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtQuantidadeItemKeyReleased

        //Coloca no padrão de reais somente 2 casas após a vírgula
        DecimalFormat df = new DecimalFormat();
        df.setMaximumFractionDigits(2);
        TotalItem = (Double.parseDouble(TxtValorItem.getText()) * (Integer.parseInt(TxtQuantidadeItem.getText())));
        LbValorTotalItem.setText((Double.toString(TotalItem)));
    }//GEN-LAST:event_TxtQuantidadeItemKeyReleased

    private void jBInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInserirActionPerformed
        if (CodCompra2 == null || CodCompra2.equals("")) {
            JOptionPane.showMessageDialog(null, "Selecione uma Compra!!");
        } else {
            SalvarItemCompra();
        }
    }//GEN-LAST:event_jBInserirActionPerformed

    private void jBFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFinalizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaItensCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaItensCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaItensCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaItensCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaItensCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTItensCompra;
    private javax.swing.JLabel LbValorTotalItem;
    private javax.swing.JTextField TxtDescItem;
    private javax.swing.JTextField TxtQuantidadeItem;
    private javax.swing.JTextField TxtValorItem;
    private javax.swing.JButton jBFinalizar;
    private javax.swing.JButton jBInserir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
