/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Dao.DinheiroGuardadoDao;
import Modelo.DinheiroGuardado;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Suporte T.I 2
 */
public class TelaDinheiroGuardado extends javax.swing.JFrame {

    /**
     * Creates new form TelaCliente
     */
    public TelaDinheiroGuardado() {
        initComponents();
        MostrarCliente();
        ButtonLocal.setSelected(true);
        TxtLocalGuardado.requestFocus();
    }

    //carrega Tabela
    public void MostrarCliente() {
        JTDinheiroGuardado.getColumnModel().getColumn(0).setPreferredWidth(60);
        JTDinheiroGuardado.getColumnModel().getColumn(1).setPreferredWidth(200);
        JTDinheiroGuardado.getColumnModel().getColumn(2).setPreferredWidth(70);
        DefaultTableModel modelo = (DefaultTableModel) JTDinheiroGuardado.getModel();
        modelo.setNumRows(0);
        DinheiroGuardadoDao cdao = new DinheiroGuardadoDao();

        cdao.BuscarDinheiro().forEach((c) -> {
            modelo.addRow(new Object[]{
                c.getCod_dinheiro(),
                c.getLocal_dinheiro(),
                c.getValor_guardado()
            });
        });
    }

    //Limpar Campos
    public void LimparCampos() {
        TxtCod.setText("");
        TxtLocalGuardado.setText("");
        TxtValorGuardado.setText("");
    }

    public void Atualizar() {
        DinheiroGuardado c = new DinheiroGuardado();
        DinheiroGuardadoDao cdao = new DinheiroGuardadoDao();
        if (TxtLocalGuardado.getText() == null || TxtLocalGuardado.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Local é Obrigatório!!");
            TxtLocalGuardado.requestFocus();
        } else if (TxtValorGuardado.getText() == null || TxtValorGuardado.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Valor é um campo obrigatório!");
            TxtValorGuardado.requestFocus();
        } else if (TxtCod.getText() == null || TxtCod.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Nenhum dado coletado");
            TxtValorGuardado.requestFocus();
        } else {
            c.setCod_dinheiro(Integer.parseInt(TxtCod.getText()));
            c.setLocal_dinheiro(TxtLocalGuardado.getText());
            c.setValor_guardado(Double.parseDouble(TxtValorGuardado.getText()));
            cdao.AtualizarDinheiro(c);
            MostrarCliente();
            LimparCampos();
        }
    }

    public void Salvar() {
        DinheiroGuardado c = new DinheiroGuardado();
        DinheiroGuardadoDao cdao = new DinheiroGuardadoDao();
        if (TxtLocalGuardado.getText() == null || TxtLocalGuardado.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Local é Obrigatório!!");
            TxtLocalGuardado.requestFocus();
        } else if (TxtValorGuardado.getText() == null || TxtValorGuardado.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Valor é um campo obrigatório!");
            TxtValorGuardado.requestFocus();
        } else {
            c.setLocal_dinheiro(TxtLocalGuardado.getText());
            c.setValor_guardado(Double.parseDouble(TxtValorGuardado.getText()));
            cdao.SalvarDinheiro(c);
            MostrarCliente();
            LimparCampos();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtCod = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtLocalGuardado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Salvar = new javax.swing.JButton();
        Salvar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTDinheiroGuardado = new javax.swing.JTable();
        ButtonCodigo = new javax.swing.JRadioButton();
        ButtonLocal = new javax.swing.JRadioButton();
        TxtPesquisa = new javax.swing.JTextField();
        ButtonValor = new javax.swing.JRadioButton();
        TxtValorGuardado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dinheiro Guardado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        jLabel2.setText("Código");

        TxtCod.setEditable(false);
        TxtCod.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        jLabel3.setText("Local");

        TxtLocalGuardado.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        jLabel4.setText("Valor");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opções", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 18))); // NOI18N

        Salvar.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        Salvar.setText("Salvar");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });

        Salvar1.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        Salvar1.setText("Pesquisar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Salvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Salvar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Salvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Salvar1)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        JTDinheiroGuardado.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        JTDinheiroGuardado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Local Guardado", "Valor"
            }
        ));
        JTDinheiroGuardado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTDinheiroGuardadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTDinheiroGuardado);

        buttonGroup1.add(ButtonCodigo);
        ButtonCodigo.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        ButtonCodigo.setText("Código");

        buttonGroup1.add(ButtonLocal);
        ButtonLocal.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        ButtonLocal.setText("Local");

        TxtPesquisa.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N

        buttonGroup1.add(ButtonValor);
        ButtonValor.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        ButtonValor.setText("Valor");

        TxtValorGuardado.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(TxtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtValorGuardado, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtLocalGuardado, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ButtonCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonLocal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonValor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtPesquisa))
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TxtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TxtLocalGuardado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TxtValorGuardado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCodigo)
                    .addComponent(ButtonLocal)
                    .addComponent(TxtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonValor))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        if (TxtCod.getText() == null || TxtCod.getText().equals("")) {
            Salvar();
            jPanel1.requestFocus();
        } else {
            Atualizar();
            jPanel1.requestFocus();
        }
        
    }//GEN-LAST:event_SalvarActionPerformed

    private void JTDinheiroGuardadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTDinheiroGuardadoMouseClicked
        if (JTDinheiroGuardado.getSelectedRow() != -1) {
            TxtCod.setText(JTDinheiroGuardado.getValueAt(JTDinheiroGuardado.getSelectedRow(), 0).toString());
            TxtLocalGuardado.setText(JTDinheiroGuardado.getValueAt(JTDinheiroGuardado.getSelectedRow(), 1).toString());
            TxtValorGuardado.setText(JTDinheiroGuardado.getValueAt(JTDinheiroGuardado.getSelectedRow(), 2).toString());
        }
    }//GEN-LAST:event_JTDinheiroGuardadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDinheiroGuardado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDinheiroGuardado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDinheiroGuardado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDinheiroGuardado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDinheiroGuardado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ButtonCodigo;
    private javax.swing.JRadioButton ButtonLocal;
    private javax.swing.JRadioButton ButtonValor;
    private javax.swing.JTable JTDinheiroGuardado;
    private javax.swing.JButton Salvar;
    private javax.swing.JButton Salvar1;
    private javax.swing.JTextField TxtCod;
    private javax.swing.JTextField TxtLocalGuardado;
    private javax.swing.JTextField TxtPesquisa;
    private javax.swing.JTextField TxtValorGuardado;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
